version: "3.7"
services:
  myfacebook_dialog_postgres:
    image: postgres:12
    container_name: myfacebook_dialog_postgres
    restart: unless-stopped
    ports:
      - "54323:5432"
    volumes:
      - ./storage/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - myfacebook

  myfacebook_dialog:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: myfacebook_dialog
    depends_on:
      - myfacebook_dialog_postgres
    restart: on-failure
    environment:
      - DB_HOST=myfacebook_dialog_postgres
      - MYFACEBOOK_API_BASE_URL=http://myfacebook:9092
      - OTEL_EXPORTER_TYPE=otel_http
      - OTEL_EXPORTER_OTLP_ENDPOINT=myfacebook_jaeger:4318
    ports:
      - ${HTTP_EXT_PORT}:${HTTP_INT_PORT}
    env_file:
      - ./.env
    networks:
      - myfacebook

networks:
  myfacebook:
    driver: bridge
    external: true